server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
        - id: ingestion-service
          uri: lb://ingestion-service
          predicates:
            - Path=/api/v1/categories/**
        - id: ingestion-service-products
          uri: lb://ingestion-service
          predicates:
            - Path=/api/v1/products/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
