apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: "{{ .Values.registry }}/discovery-server:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.discoveryServer.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.global.springProfile | quote }}
            - name: NEW_RELIC_LICENSE_KEY
              value: {{ .Values.global.apm.licenseKey | quote }}
            - name: NEW_RELIC_APP_NAME
              value: "discovery-server"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: {{ .Values.discoveryServer.port }}
      targetPort: {{ .Values.discoveryServer.port }}
